const optionList = [
    'Nifty 50',
    'NIFTY100 EQL Wgt',
    'NIFTY50 EQL Wgt',
    'NiftyM150Momntm50',
    'Nifty Auto',
    'Nifty Commodities',
   'Nifty Mid Liq 15',
    'Nifty GS 10Yr Cln',
    'NIFTY TOTAL MKT',
    'Nifty Serv Sector',
    'Nifty100 Liq 15',
    'Nifty Bank',
    'Nifty Next 50',
    'NIFTY AlphaLowVol',
    'Nifty Energy',
    'Nifty Div Opps 50',
    'NIFTY SMLCAP 50',
    'Nifty PSE',
    'NIFTY M150 QLTY50',
    'NIFTY100 LowVol30',
    'Nifty200Momentm30',
    'Nifty100ESGSecLdr',
    'Nifty GS 10Yr',
    'NIFTY Alpha 50',
    'Nifty 500',
    'Nifty Realty',
    'NIFTY INDIA MFG',
    'NIFTY200 QUALTY30',
    'Nifty GrowSect 15',
    'NIFTY100 ESG',
    'Nifty GS 8 13Yr',
    'Nifty Infra',
    'NIFTY SMLCAP 250',
    'Nifty50 PR 1x Inv',
   'NIFTY MIDCAP 100',
    'Nifty FinSrv25 50',
    'NIFTY CONSR DURBL',
    'India VIX',
    'Nifty Pharma',
    'NIFTY MIDCAP 150',
    'Nifty50 TR 1x Inv',
    'Nifty PSU Bank',
    'NIFTY HEALTHCARE',
    'NIFTY500 MULTICAP',
    'Nifty IT',
    'NIFTY MIDSML 400',
    'Nifty Media',
    'Nifty 100',
    'NIFTY100 Qualty30',
    'NIFTY LARGEMID250',
    'NIFTY SMLCAP 100',
    'Nifty Midcap 50',
    'NIFTY MICROCAP250',
    'Nifty50 PR 2x Lev',
    'Nifty200 Alpha 30',
    'Nifty Fin Service',
    'Nifty FMCG',
    'Nifty50 Value 20',
    'Nifty50 TR 2x Lev',
    'Nifty50 Div Point',
    'Nifty MNC',
    'Nifty Consumption',
    'Nifty Pvt Bank',
    'Nifty CPSE',
    'Nifty GS 11 15Yr',
    'Nifty Metal',
    'Nifty GS 15YrPlus',
    'Nifty 200',
    'NIFTY MID SELECT',
    'Nifty GS Compsite',
    'Nifty GS 4 8Yr',
    'NIFTY IND DIGITAL',
    'Nifty Tata 25 Cap',
    'Nifty Multi Mfg',
    'NIFTY OIL AND GAS',
    'Nifty MidSml Hlth',
    'Nifty Multi Infra',
]




export default optionList